In [1]:
import numpy as np

# Problem 1: SVD Mechanics and Orthogonality
np.random.seed(42)
X_prob1 = np.random.rand(5, 3)

# TODO : Compute SVD of X_prob1
U, Sigma_vals, Vt = np.linalg.svd(X_prob1, full_matrices=False)

# TODO : Reconstruct X_prob1 from U, Sigma_vals, and Vt
# Hint : Convert Sigma_vals to a proper matrix shape that allows multiplication
X_reconstructed = U @ np.diag(Sigma_vals) @ Vt

# TODO : Compute U^T @ U to verify orthogonality
U_ortho_check = U.T @ U

print("Problem 1 Results:")
if X_reconstructed is not None:
    print(f"Perfect Reconstruction? {np.allclose(X_prob1, X_reconstructed)}")
if U_ortho_check is not None:
    print(f"U^T U (should be Identity):\n{np.round(U_ortho_check, 4)}\n")

Problem 1 Results:
Perfect Reconstruction? True
U^T U (should be Identity):
[[ 1. -0.  0.]
 [-0.  1.  0.]
 [ 0.  0.  1.]]



In [2]:
# Problem 2: Low-Rank Approximation
A = np.random.rand(6, 4)
k = 2

# TODO : Compute SVD of A
U_A, Sigma_A, Vt_A = np.linalg.svd(A, full_matrices=False)

# TODO : Truncate matrices to keep only top k singular values/vectors
U_k = U_A[:, :k]
Sigma_k_matrix = np.diag(Sigma_A[:k])
Vt_k = Vt_A[:k, :]

# TODO : Compute the rank-k approximation (A_k)
A_k = U_k @ Sigma_k_matrix @ Vt_k

# TODO : Compute the Frobenius norm of the difference (Information Loss)
# Hint : Use np.linalg.norm
info_loss = np.linalg.norm(A - A_k, 'fro')

print("Problem 2 Results:")
if info_loss is not None:
    print(f"Information Lost (Frobenius Norm): {info_loss:.4f}\n")

Problem 2 Results:
Information Lost (Frobenius Norm): 0.7137



In [4]:
# Problem 3: Proving SVD is PCA
X_prob3 = np.random.rand(100, 3)

# TODO : Mean-center the data (subtract column means)
X_centered = X_prob3 - np.mean(X_prob3, axis=0)

# TODO : Compute SVD of X_centered and extract Vt
_, _, Vt_pca = np.linalg.svd(X_centered, full_matrices=False)

# TODO : Compute covariance matrix of X_centered (rowvar=False)
cov_matrix = np.cov(X_centered, rowvar=False)

# TODO : Compute eigenvectors of the covariance matrix
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
# Sort eigenvectors by eigenvalues in descending order (to match SVD order)
sorted_idx = np.argsort(eigenvalues)[::-1]
eigenvectors = eigenvectors[:, sorted_idx]

print("Problem 3 Results:")
if Vt_pca is not None and eigenvectors is not None:
    # We compare the absolute values because eigenvectors can point in opposite
    # directions (+ or -) and still represent the same principal axis.
    svd_components = np.abs(Vt_pca)
    eig_components = np.abs(eigenvectors.T)
    
    is_match = np.allclose(svd_components, eig_components)
    print(f"Do SVD right-singular vectors match PCA eigenvectors? {is_match}")

Problem 3 Results:
Do SVD right-singular vectors match PCA eigenvectors? True
