In [1]:
import numpy as np


In [2]:
# Problem 1: Matrix Multiplication vs Hadamard
A = np . array ([[1 , 2] ,
                [3 , 4]])
B = np . array ([[0 , 1] ,
                [ -1 , 0]])
# TODO : Compute standard matrix multiplication A*B and B*A
AB = np.dot(A,B)
BA = np.dot(B,A)
# TODO : Compute the element - wise product
element_wise = A * B
print (" --- Problem 1 Results ---")
print ( f"AB :\n{AB }\n")
print ( f"BA :\n{BA }\n")
print ( f" Element - wise ( Hadamard ):\n{ element_wise }\n")

 --- Problem 1 Results ---
AB :
[[-2  1]
 [-4  3]]

BA :
[[ 3  4]
 [-1 -2]]

 Element - wise ( Hadamard ):
[[ 0  2]
 [-3  0]]



In [5]:
# Problem 2: Batch Geometric Transformations
# Shape : (5 , 2) - 5 samples , 2 features (x, y)
data_points = np.array([
[1 , 1],
[2 , 1],
[2 , 2],
[1 , 2],
[1.5 , 1.5]
])

shear_matrix = np.array([
[1 , 1.5],
[0 , 1]
])
# TODO : Apply the shear matrix to ALL data points in one vectorized operation .
# Hint : S is (2 ,2). data_points is (5 ,2).
# You need to compute S @ data_points .T, then transpose the result back.
transformed_points = (shear_matrix @ data_points.T).T

print(" --- Problem 2 Results ---")
print(f"Original Points:\n{data_points}\n")
print(f"Sheared Points:\n{transformed_points}\n")

 --- Problem 2 Results ---
Original Points:
[[1.  1. ]
 [2.  1. ]
 [2.  2. ]
 [1.  2. ]
 [1.5 1.5]]

Sheared Points:
[[2.5  1.  ]
 [3.5  1.  ]
 [5.   2.  ]
 [4.   2.  ]
 [3.75 1.5 ]]



In [7]:
# Problem 3: Solving Real - World Systems
# Equations :
# 3( GPU ) + 2( CPU ) = 28
# 1( GPU ) + 4( CPU ) = 16
# TODO : Define the coefficient matrix A and the constants vector b
coeffs = np.array([[3, 2],
                   [1, 4]]) 
b = np.array([28, 16])

# TODO : Solve for the prices using np.linalg.solve
prices = np.linalg.solve(coeffs, b)
print(" --- Problem 3 Results ---")
if prices is not None:
    print(f"GPU Price per hour: ${prices[0]:.2f}")
    print(f"CPU Price per hour: ${prices[1]:.2f}")
else:          
    print("System not yet solved.")

 --- Problem 3 Results ---
GPU Price per hour: $8.00
CPU Price per hour: $2.00
